window.BUNDLED_PLAENE = [
  {
    "file": "Juli 2025.csv",
    "start": "01.07.2025",
    "end": "31.07.2025",
    "year": 2025,
    "month": 7,
    "person": {
      "last": "Bitzer",
      "first": "Jan",
      "soll": "179,40",
      "ist": "169,25",
      "urlaub": "32/0"
    },
    "days": [
      {
        "day": 1,
        "weekday": "DI",
        "code": "O"
      },
      {
        "day": 2,
        "weekday": "MI",
        "code": "10"
      },
      {
        "day": 3,
        "weekday": "DO",
        "code": "4"
      },
      {
        "day": 4,
        "weekday": "FR",
        "code": "2"
      },
      {
        "day": 5,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 6,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 7,
        "weekday": "MO",
        "code": "2"
      },
      {
        "day": 8,
        "weekday": "DI",
        "code": "N"
      },
      {
        "day": 9,
        "weekday": "MI",
        "code": "O"
      },
      {
        "day": 10,
        "weekday": "DO",
        "code": "4"
      },
      {
        "day": 11,
        "weekday": "FR",
        "code": "7"
      },
      {
        "day": 12,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 13,
        "weekday": "SO",
        "code": "N2"
      },
      {
        "day": 14,
        "weekday": "MO",
        "code": "O"
      },
      {
        "day": 15,
        "weekday": "DI",
        "code": "4"
      },
      {
        "day": 16,
        "weekday": "MI",
        "code": "10"
      },
      {
        "day": 17,
        "weekday": "DO",
        "code": "4"
      },
      {
        "day": 18,
        "weekday": "FR",
        "code": "7"
      },
      {
        "day": 19,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 20,
        "weekday": "SO",
        "code": "ST"
      },
      {
        "day": 21,
        "weekday": "MO",
        "code": "4"
      },
      {
        "day": 22,
        "weekday": "DI",
        "code": "N"
      },
      {
        "day": 23,
        "weekday": "MI",
        "code": "O"
      },
      {
        "day": 24,
        "weekday": "DO",
        "code": "10"
      },
      {
        "day": 25,
        "weekday": "FR",
        "code": "5"
      },
      {
        "day": 26,
        "weekday": "SA",
        "code": "SFT"
      },
      {
        "day": 27,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 28,
        "weekday": "MO",
        "code": "2"
      },
      {
        "day": 29,
        "weekday": "DI",
        "code": "4"
      },
      {
        "day": 30,
        "weekday": "MI",
        "code": "7"
      },
      {
        "day": 31,
        "weekday": "DO",
        "code": "4"
      }
    ],
    "team": [
      {
        "first": "Yvonne",
        "last": "Kaiser",
        "codes": [
          "U",
          "U",
          "U",
          "O",
          "O",
          "O",
          "N",
          "O",
          "4",
          "4",
          "2",
          "N2",
          "O",
          "7",
          "4",
          "4",
          "2",
          "4",
          "ST",
          "N2",
          "O",
          "7",
          "4",
          "N",
          "O",
          "O",
          "O",
          "O",
          "10",
          "4",
          "2"
        ]
      },
      {
        "first": "Melanie",
        "last": "Blüm",
        "codes": [
          "U",
          "O",
          "2",
          "7",
          "N2",
          "O",
          "10",
          "O",
          "5",
          "2",
          "O",
          "SF",
          "SF",
          "N",
          "O",
          "5",
          "O",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "10",
          "7",
          "N",
          "O"
        ]
      },
      {
        "first": "Silke",
        "last": "Metzger",
        "codes": [
          "N",
          "O",
          "5",
          "5",
          "SFT",
          "O",
          "5",
          "10",
          "7",
          "5",
          "4",
          "O",
          "O",
          "5",
          "7",
          "2",
          "10",
          "5",
          "N2",
          "O",
          "7",
          "5",
          "4",
          "2",
          "10",
          "O",
          "O",
          "N",
          "O",
          "2",
          "5"
        ]
      },
      {
        "first": "Cindy",
        "last": "Braun",
        "codes": [
          "7",
          "N",
          "O",
          "10",
          "O",
          "O",
          "O",
          "2",
          "O",
          "7",
          "N",
          "O",
          "ST",
          "2",
          "10",
          "O",
          "O",
          "O",
          "SF",
          "O",
          "O",
          "O",
          "N",
          "O",
          "2",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U"
        ]
      },
      {
        "first": "Monika",
        "last": "Glasser",
        "codes": [
          "O",
          "2",
          "12",
          "14",
          "O",
          "O",
          "14",
          "O",
          "14",
          "14",
          "12",
          "O",
          "O",
          "O",
          "2",
          "14",
          "14",
          "14",
          "O",
          "O",
          "14",
          "2",
          "12",
          "14",
          "O",
          "O",
          "O",
          "14",
          "14",
          "14",
          "O"
        ]
      },
      {
        "first": "Angela",
        "last": "Hassert",
        "codes": [
          "2",
          "5",
          "N",
          "O",
          "O",
          "O",
          "O",
          "5",
          "11",
          "N",
          "O",
          "ST",
          "O",
          "5",
          "N",
          "O",
          "7",
          "O",
          "O",
          "O",
          "O",
          "5",
          "2",
          "5",
          "7",
          "N2",
          "O",
          "5",
          "2",
          "11",
          "7"
        ]
      },
      {
        "first": "Andrea",
        "last": "Kamm",
        "codes": [
          "10",
          "5",
          "7",
          "N",
          "O",
          "ST",
          "7",
          "5",
          "N",
          "O",
          "5",
          "O",
          "O",
          "10",
          "5",
          "N",
          "O",
          "2",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U"
        ]
      },
      {
        "first": "Silke",
        "last": "Kirschbaum",
        "codes": [
          "4",
          "7",
          "4",
          "O",
          "O",
          "N2",
          "O",
          "4",
          "4",
          "10",
          "O",
          "O",
          "O",
          "O",
          "O",
          "7",
          "O",
          "10",
          "O",
          "O",
          "N",
          "O",
          "4",
          "O",
          "4",
          "O",
          "SFT",
          "O",
          "4",
          "O",
          "N"
        ]
      },
      {
        "first": "Simone",
        "last": "Kopp",
        "codes": [
          "5",
          "5",
          "O",
          "O",
          "O",
          "SF",
          "O",
          "7",
          "2",
          "5",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "N",
          "O",
          "O",
          "10",
          "O",
          "7",
          "O",
          "O",
          "O",
          "N2",
          "O",
          "O",
          "5",
          "O"
        ]
      },
      {
        "first": "Stephanie",
        "last": "Lieblang",
        "codes": [
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "AZV",
          "O",
          "N",
          "O",
          "O",
          "SF",
          "2",
          "10",
          "5",
          "7",
          "N",
          "O",
          "O",
          "7",
          "N",
          "O",
          "10"
        ]
      },
      {
        "first": "Astrid",
        "last": "Schneider",
        "codes": [
          "O",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "O",
          "O"
        ]
      }
    ]
  },
  {
    "file": "August 2025.csv",
    "start": "01.08.2025",
    "end": "31.08.2025",
    "year": 2025,
    "month": 8,
    "person": {
      "last": "Bitzer",
      "first": "Jan",
      "soll": "163,80",
      "ist": "162,08",
      "urlaub": "32/0"
    },
    "days": [
      {
        "day": 1,
        "weekday": "FR",
        "code": "10"
      },
      {
        "day": 2,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 3,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 4,
        "weekday": "MO",
        "code": "1"
      },
      {
        "day": 5,
        "weekday": "DI",
        "code": "7"
      },
      {
        "day": 6,
        "weekday": "MI",
        "code": "N"
      },
      {
        "day": 7,
        "weekday": "DO",
        "code": "O"
      },
      {
        "day": 8,
        "weekday": "FR",
        "code": "4"
      },
      {
        "day": 9,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 10,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 11,
        "weekday": "MO",
        "code": "U"
      },
      {
        "day": 12,
        "weekday": "DI",
        "code": "U"
      },
      {
        "day": 13,
        "weekday": "MI",
        "code": "U"
      },
      {
        "day": 14,
        "weekday": "DO",
        "code": "U"
      },
      {
        "day": 15,
        "weekday": "FR",
        "code": "U"
      },
      {
        "day": 16,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 17,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 18,
        "weekday": "MO",
        "code": "U"
      },
      {
        "day": 19,
        "weekday": "DI",
        "code": "U"
      },
      {
        "day": 20,
        "weekday": "MI",
        "code": "U"
      },
      {
        "day": 21,
        "weekday": "DO",
        "code": "U"
      },
      {
        "day": 22,
        "weekday": "FR",
        "code": "U"
      },
      {
        "day": 23,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 24,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 25,
        "weekday": "MO",
        "code": "1"
      },
      {
        "day": 26,
        "weekday": "DI",
        "code": "7"
      },
      {
        "day": 27,
        "weekday": "MI",
        "code": "4"
      },
      {
        "day": 28,
        "weekday": "DO",
        "code": "10"
      },
      {
        "day": 29,
        "weekday": "FR",
        "code": "N"
      },
      {
        "day": 30,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 31,
        "weekday": "SO",
        "code": "ST"
      }
    ],
    "team": [
      {
        "first": "Yvonne",
        "last": "Kaiser",
        "codes": [
          "7",
          "O",
          "ST",
          "5",
          "4",
          "2",
          "N",
          "O",
          "O",
          "O",
          "O",
          "N",
          "O",
          "4",
          "4",
          "O",
          "ST",
          "4",
          "4",
          "4",
          "4",
          "2",
          "N2",
          "O",
          "10",
          "2",
          "4",
          "4",
          "5",
          "O",
          "O"
        ]
      },
      {
        "first": "Melanie",
        "last": "Blüm",
        "codes": [
          "O",
          "O",
          "SF",
          "5",
          "5",
          "O",
          "2",
          "10",
          "O",
          "N2",
          "O",
          "O",
          "7",
          "5",
          "O",
          "ST",
          "O",
          "O",
          "10",
          "5",
          "5",
          "O",
          "O",
          "O",
          "U",
          "U",
          "O",
          "7",
          "2",
          "N2",
          "O"
        ]
      },
      {
        "first": "Silke",
        "last": "Metzger",
        "codes": [
          "5",
          "SFT",
          "O",
          "N",
          "O",
          "4",
          "5",
          "2",
          "N2",
          "O",
          "10",
          "7",
          "5",
          "2",
          "4",
          "O",
          "O",
          "7",
          "2",
          "10",
          "5",
          "5",
          "ST",
          "O",
          "N",
          "O",
          "O",
          "U",
          "U",
          "O",
          "O"
        ]
      },
      {
        "first": "Cindy",
        "last": "Braun",
        "codes": [
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "10",
          "7",
          "N",
          "O",
          "O",
          "SF",
          "O",
          "O",
          "N",
          "O",
          "O",
          "O",
          "O",
          "SF"
        ]
      },
      {
        "first": "Monika",
        "last": "Glasser",
        "codes": [
          "U",
          "O",
          "O",
          "O",
          "O",
          "12",
          "14",
          "14",
          "O",
          "O",
          "14",
          "2",
          "O",
          "14",
          "12",
          "O",
          "O",
          "14",
          "14",
          "O",
          "2",
          "14",
          "O",
          "O",
          "14",
          "O",
          "14",
          "14",
          "14",
          "O",
          "O"
        ]
      },
      {
        "first": "Angela",
        "last": "Hassert",
        "codes": [
          "5",
          "O",
          "N2",
          "O",
          "11",
          "O",
          "7",
          "O",
          "O",
          "O",
          "5",
          "5",
          "2",
          "7",
          "N",
          "O",
          "O",
          "O",
          "N",
          "O",
          "5",
          "11",
          "O",
          "O",
          "5",
          "O",
          "11",
          "2",
          "7",
          "ST",
          "O"
        ]
      },
      {
        "first": "Andrea",
        "last": "Kamm",
        "codes": [
          "U",
          "O",
          "O",
          "U",
          "2",
          "O",
          "5",
          "N",
          "O",
          "ST",
          "O",
          "5",
          "10",
          "N",
          "O",
          "O",
          "SF",
          "2",
          "O",
          "7",
          "10",
          "5",
          "O",
          "O",
          "7",
          "5",
          "N",
          "O",
          "O",
          "SF",
          "O"
        ]
      },
      {
        "first": "Silke",
        "last": "Kirschbaum",
        "codes": [
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "N",
          "O",
          "4",
          "O",
          "7",
          "O",
          "SFT",
          "O",
          "10",
          "7",
          "4",
          "O",
          "O",
          "N2"
        ]
      },
      {
        "first": "Simone",
        "last": "Kopp",
        "codes": [
          "O",
          "O",
          "O",
          "O",
          "O",
          "7",
          "O",
          "O",
          "O",
          "SF",
          "7",
          "O",
          "O",
          "O",
          "2",
          "N2",
          "O",
          "O",
          "O",
          "O",
          "5",
          "N",
          "O",
          "O",
          "O",
          "O",
          "O",
          "N",
          "O",
          "O",
          "O"
        ]
      },
      {
        "first": "Stephanie",
        "last": "Lieblang",
        "codes": [
          "2",
          "N2",
          "O",
          "10",
          "5",
          "5",
          "5",
          "7",
          "O",
          "O",
          "N",
          "O",
          "5",
          "10",
          "7",
          "SF",
          "N2",
          "O",
          "5",
          "2",
          "N",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O"
        ]
      },
      {
        "first": "Astrid",
        "last": "Schneider",
        "codes": [
          "N",
          "O",
          "O",
          "7",
          "N",
          "O",
          "10",
          "5",
          "SFT",
          "O",
          "2",
          "10",
          "N",
          "O",
          "5",
          "O",
          "O",
          "5",
          "5",
          "5",
          "7",
          "O",
          "O",
          "N2",
          "O",
          "5",
          "2",
          "5",
          "10",
          "O",
          "O"
        ]
      }
    ]
  },
  {
    "file": "Oktober 2025.csv",
    "start": "01.10.2025",
    "end": "31.10.2025",
    "year": 2025,
    "month": 10,
    "person": {
      "last": "Bitzer",
      "first": "Jan",
      "soll": "171,60",
      "ist": "175,50",
      "urlaub": "32/0"
    },
    "days": [
      {
        "day": 1,
        "weekday": "MI",
        "code": "4"
      },
      {
        "day": 2,
        "weekday": "DO",
        "code": "4"
      },
      {
        "day": 3,
        "weekday": "FR",
        "code": "O"
      },
      {
        "day": 4,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 5,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 6,
        "weekday": "MO",
        "code": "N"
      },
      {
        "day": 7,
        "weekday": "DI",
        "code": "O"
      },
      {
        "day": 8,
        "weekday": "MI",
        "code": "7"
      },
      {
        "day": 9,
        "weekday": "DO",
        "code": "4"
      },
      {
        "day": 10,
        "weekday": "FR",
        "code": "1"
      },
      {
        "day": 11,
        "weekday": "SA",
        "code": "SFT"
      },
      {
        "day": 12,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 13,
        "weekday": "MO",
        "code": "GSB"
      },
      {
        "day": 14,
        "weekday": "DI",
        "code": "N"
      },
      {
        "day": 15,
        "weekday": "MI",
        "code": "O"
      },
      {
        "day": 16,
        "weekday": "DO",
        "code": "10"
      },
      {
        "day": 17,
        "weekday": "FR",
        "code": "4"
      },
      {
        "day": 18,
        "weekday": "SA",
        "code": "N2"
      },
      {
        "day": 19,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 20,
        "weekday": "MO",
        "code": "4"
      },
      {
        "day": 21,
        "weekday": "DI",
        "code": "7"
      },
      {
        "day": 22,
        "weekday": "MI",
        "code": "1"
      },
      {
        "day": 23,
        "weekday": "DO",
        "code": "4"
      },
      {
        "day": 24,
        "weekday": "FR",
        "code": "10"
      },
      {
        "day": 25,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 26,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 27,
        "weekday": "MO",
        "code": "4"
      },
      {
        "day": 28,
        "weekday": "DI",
        "code": "4"
      },
      {
        "day": 29,
        "weekday": "MI",
        "code": "4"
      },
      {
        "day": 30,
        "weekday": "DO",
        "code": "7"
      },
      {
        "day": 31,
        "weekday": "FR",
        "code": "GSB"
      }
    ],
    "team": [
      {
        "first": "Yvonne",
        "last": "Kaiser",
        "codes": [
          "4",
          "10",
          "O",
          "N2",
          "O",
          "4",
          "4",
          "4",
          "4",
          "4",
          "O",
          "ST",
          "4",
          "4",
          "4",
          "N",
          "O",
          "O",
          "O",
          "4",
          "4",
          "4",
          "4",
          "2",
          "O",
          "N2",
          "O",
          "4",
          "4",
          "2",
          "4"
        ]
      },
      {
        "first": "Melanie",
        "last": "Blüm",
        "codes": [
          "U",
          "U",
          "O",
          "O",
          "O",
          "10",
          "O",
          "5",
          "N",
          "O",
          "O",
          "SF",
          "O",
          "7",
          "10",
          "5",
          "2",
          "O",
          "O",
          "7",
          "10",
          "N",
          "O",
          "5",
          "SFT",
          "O",
          "O",
          "O",
          "5",
          "5",
          "O"
        ]
      },
      {
        "first": "Silke",
        "last": "Metzger",
        "codes": [
          "2",
          "5",
          "O",
          "O",
          "O",
          "5",
          "5",
          "10",
          "5",
          "7",
          "N2",
          "O",
          "10",
          "5",
          "7",
          "2",
          "5",
          "SFT",
          "O",
          "4",
          "N",
          "O",
          "5",
          "5",
          "O",
          "O",
          "10",
          "N",
          "O",
          "5",
          "2"
        ]
      },
      {
        "first": "Cindy",
        "last": "Braun",
        "codes": [
          "O",
          "N",
          "O",
          "O",
          "O",
          "2",
          "10",
          "O",
          "O",
          "N",
          "O",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "N",
          "O",
          "10",
          "5",
          "7"
        ]
      },
      {
        "first": "Monika",
        "last": "Glasser",
        "codes": [
          "U",
          "U",
          "O",
          "O",
          "O",
          "O",
          "14",
          "14",
          "12",
          "14",
          "O",
          "O",
          "14",
          "2",
          "14",
          "O",
          "12",
          "O",
          "O",
          "2",
          "14",
          "O",
          "14",
          "14",
          "O",
          "O",
          "14",
          "14",
          "2",
          "O",
          "14"
        ]
      },
      {
        "first": "Angela",
        "last": "Hassert",
        "codes": [
          "N",
          "O",
          "ST",
          "O",
          "O",
          "5",
          "2",
          "N",
          "O",
          "5",
          "O",
          "O",
          "7",
          "11",
          "5",
          "5",
          "N",
          "O",
          "ST",
          "11",
          "5",
          "5",
          "7",
          "O",
          "N2",
          "O",
          "O",
          "2",
          "7",
          "O",
          "5"
        ]
      },
      {
        "first": "Andrea",
        "last": "Kamm",
        "codes": [
          "O",
          "2",
          "SF",
          "O",
          "N2",
          "O",
          "7",
          "O",
          "2",
          "10",
          "O",
          "O",
          "5",
          "4",
          "N",
          "O",
          "7",
          "O",
          "SF",
          "4",
          "2",
          "10",
          "N",
          "O",
          "O",
          "O",
          "5",
          "7",
          "4",
          "10",
          "O"
        ]
      },
      {
        "first": "Silke",
        "last": "Kirschbaum",
        "codes": [
          "7",
          "O",
          "O",
          "O",
          "SFT",
          "4",
          "O",
          "4",
          "O",
          "4",
          "O",
          "N2",
          "O",
          "O",
          "4",
          "4",
          "4",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U"
        ]
      },
      {
        "first": "Simone",
        "last": "Kopp",
        "codes": [
          "O",
          "O",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "O",
          "O",
          "2",
          "7",
          "O",
          "O",
          "N2",
          "O",
          "O",
          "7",
          "5",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "N",
          "O"
        ]
      },
      {
        "first": "Stephanie",
        "last": "Lieblang",
        "codes": [
          "5",
          "7",
          "N2",
          "O",
          "O",
          "5",
          "4",
          "2",
          "7",
          "4",
          "O",
          "O",
          "N",
          "O",
          "U",
          "U",
          "U",
          "O",
          "O",
          "N",
          "O",
          "5",
          "10",
          "N",
          "O",
          "ST",
          "2",
          "10",
          "4",
          "5",
          "N"
        ]
      },
      {
        "first": "Astrid",
        "last": "Schneider",
        "codes": [
          "10",
          "5",
          "O",
          "SFT",
          "O",
          "7",
          "N",
          "O",
          "O",
          "O",
          "O",
          "O",
          "2",
          "5",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "2",
          "7",
          "O",
          "SF",
          "7",
          "5",
          "N",
          "O",
          "10"
        ]
      }
    ]
  },
  {
    "file": "November 2025.csv",
    "start": "01.11.2025",
    "end": "30.11.2025",
    "year": 2025,
    "month": 11,
    "person": {
      "last": "Bitzer",
      "first": "Jan",
      "soll": "156,00",
      "ist": "159,25",
      "urlaub": "32/0"
    },
    "days": [
      {
        "day": 1,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 2,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 3,
        "weekday": "MO",
        "code": "U"
      },
      {
        "day": 4,
        "weekday": "DI",
        "code": "U"
      },
      {
        "day": 5,
        "weekday": "MI",
        "code": "U"
      },
      {
        "day": 6,
        "weekday": "DO",
        "code": "U"
      },
      {
        "day": 7,
        "weekday": "FR",
        "code": "U"
      },
      {
        "day": 8,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 9,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 10,
        "weekday": "MO",
        "code": "10"
      },
      {
        "day": 11,
        "weekday": "DI",
        "code": "N"
      },
      {
        "day": 12,
        "weekday": "MI",
        "code": "O"
      },
      {
        "day": 13,
        "weekday": "DO",
        "code": "5"
      },
      {
        "day": 14,
        "weekday": "FR",
        "code": "4"
      },
      {
        "day": 15,
        "weekday": "SA",
        "code": "SFT"
      },
      {
        "day": 16,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 17,
        "weekday": "MO",
        "code": "2"
      },
      {
        "day": 18,
        "weekday": "DI",
        "code": "5"
      },
      {
        "day": 19,
        "weekday": "MI",
        "code": "7"
      },
      {
        "day": 20,
        "weekday": "DO",
        "code": "4"
      },
      {
        "day": 21,
        "weekday": "FR",
        "code": "GSB"
      },
      {
        "day": 22,
        "weekday": "SA",
        "code": "N2"
      },
      {
        "day": 23,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 24,
        "weekday": "MO",
        "code": "7"
      },
      {
        "day": 25,
        "weekday": "DI",
        "code": "2"
      },
      {
        "day": 26,
        "weekday": "MI",
        "code": "10"
      },
      {
        "day": 27,
        "weekday": "DO",
        "code": "5"
      },
      {
        "day": 28,
        "weekday": "FR",
        "code": "N"
      },
      {
        "day": 29,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 30,
        "weekday": "SO",
        "code": "O"
      }
    ],
    "team": [
      {
        "first": "Juliana",
        "last": "Brandenburger",
        "codes": [
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "4",
          "4",
          "4",
          "4",
          "4",
          "O",
          "O",
          "4",
          "4",
          "4",
          "4",
          "4",
          "O",
          "O"
        ]
      },
      {
        "first": "Yvonne",
        "last": "Kaiser",
        "codes": [
          "O",
          "O",
          "N",
          "O",
          "4",
          "4",
          "2",
          "O",
          "O",
          "4",
          "4",
          "5",
          "4",
          "O",
          "N2",
          "O",
          "4",
          "4",
          "4",
          "4",
          "4",
          "O",
          "ST",
          "2",
          "7",
          "4",
          "N",
          "O",
          "O",
          "SF"
        ]
      },
      {
        "first": "Melanie",
        "last": "Blüm",
        "codes": [
          "O",
          "N",
          "O",
          "7",
          "2",
          "10",
          "O",
          "O",
          "O",
          "5",
          "5",
          "N",
          "O",
          "7",
          "O",
          "O",
          "5",
          "2",
          "O",
          "O",
          "10",
          "O",
          "O",
          "10",
          "5",
          "5",
          "5",
          "5",
          "SFT",
          "O"
        ]
      },
      {
        "first": "Silke",
        "last": "Metzger",
        "codes": [
          "O",
          "O",
          "10",
          "5",
          "7",
          "N",
          "O",
          "O",
          "O",
          "AZV",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "N",
          "O",
          "10",
          "7",
          "2",
          "SFT",
          "O",
          "5",
          "5",
          "2",
          "5",
          "10",
          "N2",
          "O"
        ]
      },
      {
        "first": "Cindy",
        "last": "Braun",
        "codes": [
          "N2",
          "O",
          "5",
          "2",
          "10",
          "5",
          "O",
          "O",
          "N2",
          "O",
          "O",
          "7",
          "2",
          "O",
          "O",
          "ST",
          "5",
          "7",
          "N",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "5",
          "7",
          "O",
          "O"
        ]
      },
      {
        "first": "Monika",
        "last": "Glasser",
        "codes": [
          "O",
          "O",
          "O",
          "14",
          "14",
          "2",
          "14",
          "O",
          "O",
          "2",
          "14",
          "O",
          "14",
          "12",
          "O",
          "O",
          "14",
          "O",
          "14",
          "12",
          "14",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O"
        ]
      },
      {
        "first": "Angela",
        "last": "Hassert",
        "codes": [
          "SF",
          "O",
          "5",
          "5",
          "N",
          "O",
          "11",
          "O",
          "O",
          "4",
          "2",
          "5",
          "O",
          "N",
          "O",
          "O",
          "O",
          "11",
          "5",
          "5",
          "7",
          "O",
          "SF",
          "5",
          "N",
          "O",
          "7",
          "2",
          "O",
          "O"
        ]
      },
      {
        "first": "Andrea",
        "last": "Kamm",
        "codes": [
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "4",
          "7",
          "O",
          "7",
          "2",
          "O",
          "SF",
          "7",
          "N",
          "O",
          "5",
          "5",
          "O",
          "N2",
          "O",
          "10",
          "5",
          "2",
          "4",
          "O",
          "ST"
        ]
      },
      {
        "first": "Silke",
        "last": "Kirschbaum",
        "codes": [
          "O",
          "O",
          "4",
          "O",
          "4",
          "O",
          "7",
          "O",
          "SFT",
          "4",
          "4",
          "O",
          "4",
          "DB",
          "O",
          "O",
          "DB",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "N",
          "O",
          "7",
          "10",
          "O",
          "O",
          "N2"
        ]
      },
      {
        "first": "Simone",
        "last": "Kopp",
        "codes": [
          "ST",
          "ST",
          "O",
          "5",
          "O",
          "O",
          "N",
          "O",
          "O",
          "5",
          "O",
          "10",
          "O",
          "5",
          "O",
          "N2",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O"
        ]
      },
      {
        "first": "Stephanie",
        "last": "Lieblang",
        "codes": [
          "O",
          "SF",
          "7",
          "N",
          "O",
          "5",
          "5",
          "N2",
          "O",
          "N",
          "O",
          "2",
          "10",
          "5",
          "O",
          "O",
          "10",
          "4",
          "2",
          "N",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O"
        ]
      },
      {
        "first": "Astrid",
        "last": "Schneider",
        "codes": [
          "O",
          "O",
          "2",
          "10",
          "5",
          "7",
          "5",
          "SFT",
          "O",
          "7",
          "10",
          "5",
          "N",
          "O",
          "O",
          "O",
          "5",
          "5",
          "5",
          "2",
          "N",
          "O",
          "O",
          "O",
          "5",
          "N",
          "O",
          "5",
          "O",
          "O"
        ]
      }
    ]
  },
  {
    "file": "Dezember 2025.csv",
    "start": "01.12.2025",
    "end": "31.12.2025",
    "year": 2025,
    "month": 12,
    "person": {
      "last": "Bitzer",
      "first": "Jan",
      "soll": "148,20",
      "ist": "154,25",
      "urlaub": "32/0"
    },
    "days": [
      {
        "day": 1,
        "weekday": "MO",
        "code": "10"
      },
      {
        "day": 2,
        "weekday": "DI",
        "code": "4"
      },
      {
        "day": 3,
        "weekday": "MI",
        "code": "1"
      },
      {
        "day": 4,
        "weekday": "DO",
        "code": "7"
      },
      {
        "day": 5,
        "weekday": "FR",
        "code": "4"
      },
      {
        "day": 6,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 7,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 8,
        "weekday": "MO",
        "code": "4"
      },
      {
        "day": 9,
        "weekday": "DI",
        "code": "4"
      },
      {
        "day": 10,
        "weekday": "MI",
        "code": "4"
      },
      {
        "day": 11,
        "weekday": "DO",
        "code": "7"
      },
      {
        "day": 12,
        "weekday": "FR",
        "code": "2"
      },
      {
        "day": 13,
        "weekday": "SA",
        "code": "N2"
      },
      {
        "day": 14,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 15,
        "weekday": "MO",
        "code": "10"
      },
      {
        "day": 16,
        "weekday": "DI",
        "code": "4"
      },
      {
        "day": 17,
        "weekday": "MI",
        "code": "4"
      },
      {
        "day": 18,
        "weekday": "DO",
        "code": "N"
      },
      {
        "day": 19,
        "weekday": "FR",
        "code": "O"
      },
      {
        "day": 20,
        "weekday": "SA",
        "code": "ST"
      },
      {
        "day": 21,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 22,
        "weekday": "MO",
        "code": "4"
      },
      {
        "day": 23,
        "weekday": "DI",
        "code": "1"
      },
      {
        "day": 24,
        "weekday": "MI",
        "code": "O"
      },
      {
        "day": 25,
        "weekday": "DO",
        "code": "O"
      },
      {
        "day": 26,
        "weekday": "FR",
        "code": "O"
      },
      {
        "day": 27,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 28,
        "weekday": "SO",
        "code": "N2"
      },
      {
        "day": 29,
        "weekday": "MO",
        "code": "O"
      },
      {
        "day": 30,
        "weekday": "DI",
        "code": "7"
      },
      {
        "day": 31,
        "weekday": "MI",
        "code": "ST"
      }
    ],
    "team": [
      {
        "first": "Juliana",
        "last": "Brandenburger",
        "codes": [
          "5",
          "5",
          "5",
          "5",
          "5",
          "O",
          "O",
          "5",
          "5",
          "5",
          "5",
          "5",
          "O",
          "O",
          "5",
          "5",
          "5",
          "5",
          "5",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          ""
        ]
      },
      {
        "first": "Yvonne",
        "last": "Kaiser",
        "codes": [
          "4",
          "2",
          "5",
          "N",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "4",
          "4",
          "4",
          "7",
          "N2",
          "O",
          "4",
          "1",
          "ST",
          "O",
          "O",
          "N2",
          "O",
          "O",
          "2",
          "O"
        ]
      },
      {
        "first": "Melanie",
        "last": "Blüm",
        "codes": [
          "5",
          "7",
          "5",
          "10",
          "N",
          "O",
          "O",
          "2",
          "AZV",
          "U",
          "U",
          "U",
          "O",
          "O",
          "O",
          "O",
          "2",
          "7",
          "5",
          "SF",
          "O",
          "O",
          "N",
          "O",
          "O",
          "O",
          "O",
          "SF",
          "O",
          "10",
          "O"
        ]
      },
      {
        "first": "Silke",
        "last": "Metzger",
        "codes": [
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "10",
          "7",
          "2",
          "5",
          "5",
          "O",
          "SFT",
          "2",
          "7",
          "N",
          "O",
          "10",
          "O",
          "N2",
          "O",
          "4",
          "O",
          "O",
          "O",
          "ST",
          "O",
          "7",
          "N",
          "O"
        ]
      },
      {
        "first": "Cindy",
        "last": "Braun",
        "codes": [
          "N",
          "O",
          "10",
          "5",
          "O",
          "SF",
          "O",
          "7",
          "N",
          "O",
          "O",
          "10",
          "O",
          "N2",
          "O",
          "5",
          "7",
          "2",
          "O",
          "O",
          "O",
          "U",
          "U",
          "SF",
          "O",
          "O",
          "O",
          "O",
          "AZV",
          "O",
          "O"
        ]
      },
      {
        "first": "Monika",
        "last": "Glasser",
        "codes": [
          "U",
          "AZV",
          "U",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "12",
          "14",
          "14",
          "O",
          "O",
          "14",
          "O",
          "14",
          "14",
          "14",
          "O",
          "ST",
          "2",
          "12",
          "O",
          "O",
          "O",
          "O",
          "O",
          "2",
          "14",
          "O"
        ]
      },
      {
        "first": "Angela",
        "last": "Hassert",
        "codes": [
          "7",
          "O",
          "O",
          "O",
          "2",
          "O",
          "SFT",
          "N",
          "O",
          "7",
          "2",
          "O",
          "O",
          "O",
          "N",
          "O",
          "AZV",
          "U",
          "U",
          "O",
          "O",
          "11",
          "5",
          "O",
          "SF",
          "SF",
          "O",
          "O",
          "U",
          "U",
          "O"
        ]
      },
      {
        "first": "Andrea",
        "last": "Kamm",
        "codes": [
          "5",
          "10",
          "7",
          "1",
          "AZV",
          "O",
          "O",
          "U",
          "U",
          "U",
          "LZK",
          "LZK",
          "LZK",
          "LZK",
          "LZK",
          "LZK",
          "LZK",
          "LZK",
          "LZK",
          "O",
          "O",
          "N",
          "O",
          "O",
          "ST",
          "O",
          "O",
          "O",
          "N",
          "O",
          "O"
        ]
      },
      {
        "first": "Silke",
        "last": "Kirschbaum",
        "codes": [
          "O",
          "4",
          "O",
          "O",
          "10",
          "O",
          "N2",
          "O",
          "4",
          "4",
          "O",
          "4",
          "O",
          "O",
          "O",
          "N",
          "O",
          "4",
          "4",
          "O",
          "O",
          "U",
          "U",
          "O",
          "O",
          "ST",
          "O",
          "O",
          "U",
          "AZV",
          "N2"
        ]
      },
      {
        "first": "Simone",
        "last": "Kopp",
        "codes": [
          "U",
          "AZV",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "2",
          "N",
          "O",
          "7",
          "SF",
          "O",
          "O",
          "O",
          "10",
          "O",
          "N",
          "O",
          "O",
          "7",
          "O",
          "O",
          "N2",
          "O",
          "SF",
          "O",
          "10",
          "O",
          "SF"
        ]
      },
      {
        "first": "Stephanie",
        "last": "Lieblang",
        "codes": [
          "2",
          "N",
          "O",
          "5",
          "5",
          "N2",
          "O",
          "4",
          "10",
          "5",
          "N",
          "O",
          "ST",
          "O",
          "5",
          "10",
          "5",
          "5",
          "2",
          "O",
          "SF",
          "5",
          "7",
          "N2",
          "O",
          "O",
          "O",
          "O",
          "5",
          "7",
          "O"
        ]
      },
      {
        "first": "Astrid",
        "last": "Schneider",
        "codes": [
          "AZV",
          "O",
          "N",
          "O",
          "7",
          "ST",
          "O",
          "5",
          "5",
          "5",
          "10",
          "N",
          "O",
          "O",
          "7",
          "2",
          "O",
          "10",
          "5",
          "O",
          "O",
          "U",
          "U",
          "O",
          "O",
          "N2",
          "O",
          "ST",
          "5",
          "5",
          "O"
        ]
      }
    ]
  },
  {
    "file": "Januar 2026.csv",
    "start": "01.01.2026",
    "end": "31.01.2026",
    "year": 2026,
    "month": 1,
    "person": {
      "last": "Bitzer",
      "first": "Jan",
      "soll": "163,80",
      "ist": "168,33",
      "urlaub": "33/22"
    },
    "days": [
      {
        "day": 1,
        "weekday": "DO",
        "code": "O"
      },
      {
        "day": 2,
        "weekday": "FR",
        "code": "5"
      },
      {
        "day": 3,
        "weekday": "SA",
        "code": "N2"
      },
      {
        "day": 4,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 5,
        "weekday": "MO",
        "code": "10"
      },
      {
        "day": 6,
        "weekday": "DI",
        "code": "7"
      },
      {
        "day": 7,
        "weekday": "MI",
        "code": "2"
      },
      {
        "day": 8,
        "weekday": "DO",
        "code": "GSB"
      },
      {
        "day": 9,
        "weekday": "FR",
        "code": "4"
      },
      {
        "day": 10,
        "weekday": "SA",
        "code": "SFT"
      },
      {
        "day": 11,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 12,
        "weekday": "MO",
        "code": "7"
      },
      {
        "day": 13,
        "weekday": "DI",
        "code": "GSB"
      },
      {
        "day": 14,
        "weekday": "MI",
        "code": "10"
      },
      {
        "day": 15,
        "weekday": "DO",
        "code": "5"
      },
      {
        "day": 16,
        "weekday": "FR",
        "code": "5"
      },
      {
        "day": 17,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 18,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 19,
        "weekday": "MO",
        "code": "5"
      },
      {
        "day": 20,
        "weekday": "DI",
        "code": "2"
      },
      {
        "day": 21,
        "weekday": "MI",
        "code": "GSB"
      },
      {
        "day": 22,
        "weekday": "DO",
        "code": "7"
      },
      {
        "day": 23,
        "weekday": "FR",
        "code": "5"
      },
      {
        "day": 24,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 25,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 26,
        "weekday": "MO",
        "code": "5"
      },
      {
        "day": 27,
        "weekday": "DI",
        "code": "7"
      },
      {
        "day": 28,
        "weekday": "MI",
        "code": "GSB"
      },
      {
        "day": 29,
        "weekday": "DO",
        "code": "4"
      },
      {
        "day": 30,
        "weekday": "FR",
        "code": "N"
      },
      {
        "day": 31,
        "weekday": "SA",
        "code": "O"
      }
    ],
    "team": [
      {
        "first": "Yvonne",
        "last": "Kaiser",
        "codes": [
          "O",
          "N",
          "O",
          "O",
          "4",
          "4",
          "7",
          "O",
          "2",
          "O",
          "O",
          "N",
          "O",
          "4",
          "4",
          "7",
          "N2",
          "O",
          "4",
          "4",
          "4",
          "5",
          "10",
          "O",
          "O",
          "4",
          "2",
          "4",
          "N",
          "O",
          "O"
        ]
      },
      {
        "first": "Melanie",
        "last": "Blüm",
        "codes": [
          "N2",
          "O",
          "O",
          "O",
          "5",
          "O",
          "10",
          "5",
          "7",
          "O",
          "N2",
          "O",
          "O",
          "2",
          "7",
          "5",
          "ST",
          "O",
          "O",
          "10",
          "5",
          "5",
          "O",
          "O",
          "SF",
          "2",
          "N",
          "O",
          "O",
          "5",
          "ST"
        ]
      },
      {
        "first": "Silke",
        "last": "Metzger",
        "codes": [
          "O",
          "2",
          "SFT",
          "O",
          "7",
          "5",
          "N",
          "O",
          "U",
          "O",
          "O",
          "4",
          "5",
          "N",
          "O",
          "10",
          "O",
          "ST",
          "5",
          "5",
          "7",
          "5",
          "2",
          "N2",
          "O",
          "10",
          "5",
          "7",
          "5",
          "5",
          "O"
        ]
      },
      {
        "first": "Cindy",
        "last": "Braun",
        "codes": [
          "O",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "2",
          "N",
          "O",
          "O",
          "O",
          "2",
          "O",
          "O",
          "O",
          "SF",
          "O",
          "N",
          "O",
          "10",
          "5",
          "O",
          "O",
          "N2",
          "O",
          "O",
          "10",
          "7",
          "O",
          "O"
        ]
      },
      {
        "first": "Monika",
        "last": "Glasser",
        "codes": [
          "O",
          "14",
          "O",
          "O",
          "2",
          "14",
          "O",
          "14",
          "12",
          "O",
          "O",
          "12",
          "14",
          "14",
          "O",
          "2",
          "O",
          "O",
          "O",
          "14",
          "14",
          "2",
          "14",
          "O",
          "O",
          "14",
          "14",
          "O",
          "12",
          "14",
          "O"
        ]
      },
      {
        "first": "Angela",
        "last": "Hassert",
        "codes": [
          "O",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "2",
          "N",
          "O",
          "11",
          "O",
          "O",
          "N2",
          "O",
          "7",
          "2",
          "N",
          "O",
          "O",
          "ST",
          "7",
          "O",
          "2",
          "O",
          "11",
          "N2"
        ]
      },
      {
        "first": "Andrea",
        "last": "Kamm",
        "codes": [
          "SF",
          "4",
          "O",
          "O",
          "4",
          "4",
          "5",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV"
        ]
      },
      {
        "first": "Silke",
        "last": "Kirschbaum",
        "codes": [
          "O",
          "7",
          "O",
          "ST",
          "O",
          "N",
          "O",
          "10",
          "O",
          "O",
          "SFT",
          "4",
          "O",
          "4",
          "N",
          "O",
          "O",
          "O",
          "7",
          "O",
          "O",
          "4",
          "4",
          "O",
          "O",
          "N",
          "O",
          "4",
          "4",
          "O",
          "O"
        ]
      },
      {
        "first": "Simone",
        "last": "Kopp",
        "codes": [
          "O",
          "O",
          "O",
          "O",
          "O",
          "2",
          "O",
          "N",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "O",
          "5",
          "O",
          "10",
          "N",
          "O",
          "O",
          "O",
          "5",
          "N",
          "O",
          "O",
          "SF"
        ]
      },
      {
        "first": "Stephanie",
        "last": "Lieblang",
        "codes": [
          "O",
          "10",
          "O",
          "SF",
          "N",
          "O",
          "5",
          "4",
          "5",
          "N2",
          "O",
          "4",
          "7",
          "5",
          "2",
          "5",
          "O",
          "SF",
          "10",
          "N",
          "O",
          "4",
          "7",
          "O",
          "O",
          "4",
          "10",
          "5",
          "4",
          "2",
          "O"
        ]
      },
      {
        "first": "Astrid",
        "last": "Schneider",
        "codes": [
          "ST",
          "O",
          "O",
          "N2",
          "O",
          "10",
          "5",
          "7",
          "5",
          "O",
          "O",
          "5",
          "10",
          "7",
          "5",
          "N",
          "O",
          "O",
          "2",
          "5",
          "N",
          "O",
          "5",
          "SFT",
          "O",
          "O",
          "5",
          "5",
          "2",
          "7",
          "O"
        ]
      }
    ]
  },
  {
    "file": "Februar 2026.csv",
    "start": "01.02.2026",
    "end": "28.02.2026",
    "year": 2026,
    "month": 2,
    "person": {
      "last": "Bitzer",
      "first": "Jan",
      "soll": "156,00",
      "ist": "153,30",
      "urlaub": "33/22"
    },
    "days": [
      {
        "day": 1,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 2,
        "weekday": "MO",
        "code": "5"
      },
      {
        "day": 3,
        "weekday": "DI",
        "code": "10"
      },
      {
        "day": 4,
        "weekday": "MI",
        "code": "GSB"
      },
      {
        "day": 5,
        "weekday": "DO",
        "code": "7"
      },
      {
        "day": 6,
        "weekday": "FR",
        "code": "5"
      },
      {
        "day": 7,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 8,
        "weekday": "SO",
        "code": "SFT"
      },
      {
        "day": 9,
        "weekday": "MO",
        "code": "N"
      },
      {
        "day": 10,
        "weekday": "DI",
        "code": "O"
      },
      {
        "day": 11,
        "weekday": "MI",
        "code": "7"
      },
      {
        "day": 12,
        "weekday": "DO",
        "code": "GSB"
      },
      {
        "day": 13,
        "weekday": "FR",
        "code": "10"
      },
      {
        "day": 14,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 15,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 16,
        "weekday": "MO",
        "code": "2"
      },
      {
        "day": 17,
        "weekday": "DI",
        "code": "7"
      },
      {
        "day": 18,
        "weekday": "MI",
        "code": "5"
      },
      {
        "day": 19,
        "weekday": "DO",
        "code": "GSB"
      },
      {
        "day": 20,
        "weekday": "FR",
        "code": "5"
      },
      {
        "day": 21,
        "weekday": "SA",
        "code": "N2"
      },
      {
        "day": 22,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 23,
        "weekday": "MO",
        "code": "GSB"
      },
      {
        "day": 24,
        "weekday": "DI",
        "code": "2"
      },
      {
        "day": 25,
        "weekday": "MI",
        "code": "N"
      },
      {
        "day": 26,
        "weekday": "DO",
        "code": "O"
      },
      {
        "day": 27,
        "weekday": "FR",
        "code": "U"
      },
      {
        "day": 28,
        "weekday": "SA",
        "code": "O"
      }
    ],
    "team": [
      {
        "first": "Yvonne",
        "last": "Kaiser",
        "codes": [
          "O",
          "4",
          "FB",
          "FB",
          "4",
          "2",
          "N2",
          "O",
          "4",
          "O",
          "2",
          "4",
          "4",
          "O",
          "O",
          "4",
          "4",
          "N",
          "O",
          "10",
          "O",
          "N2",
          "O",
          "4",
          "7",
          "4",
          "4",
          "ST"
        ]
      },
      {
        "first": "Melanie",
        "last": "Blüm",
        "codes": [
          "O",
          "O",
          "5",
          "10",
          "5",
          "O",
          "O",
          "O",
          "2",
          "7",
          "N",
          "O",
          "O",
          "O",
          "SFT",
          "5",
          "2",
          "10",
          "N",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O"
        ]
      },
      {
        "first": "Silke",
        "last": "Metzger",
        "codes": [
          "O",
          "5",
          "N",
          "O",
          "10",
          "4",
          "O",
          "O",
          "7",
          "5",
          "5",
          "2",
          "5",
          "N2",
          "O",
          "10",
          "5",
          "7",
          "5",
          "5",
          "SFT",
          "O",
          "2",
          "10",
          "5",
          "7",
          "O",
          "O"
        ]
      },
      {
        "first": "Cindy",
        "last": "Braun",
        "codes": [
          "O",
          "7",
          "2",
          "N",
          "O",
          "5",
          "SF",
          "O",
          "O",
          "N",
          "O",
          "O",
          "O",
          "O",
          "O",
          "U",
          "U",
          "O",
          "O",
          "N",
          "O",
          "O",
          "10",
          "5",
          "O",
          "2",
          "10",
          "O"
        ]
      },
      {
        "first": "Monika",
        "last": "Glasser",
        "codes": [
          "O",
          "14",
          "O",
          "14",
          "2",
          "12",
          "O",
          "O",
          "12",
          "O",
          "14",
          "14",
          "14",
          "O",
          "O",
          "14",
          "O",
          "14",
          "2",
          "14",
          "O",
          "O",
          "14",
          "O",
          "12",
          "14",
          "2",
          "O"
        ]
      },
      {
        "first": "Angela",
        "last": "Hassert",
        "codes": [
          "O",
          "11",
          "5",
          "7",
          "N",
          "O",
          "O",
          "O",
          "5",
          "2",
          "11",
          "N",
          "O",
          "ST",
          "O",
          "N",
          "O",
          "2",
          "O",
          "7",
          "O",
          "SF",
          "7",
          "5",
          "2",
          "O",
          "N",
          "O"
        ]
      },
      {
        "first": "Andrea",
        "last": "Kamm",
        "codes": [
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV"
        ]
      },
      {
        "first": "Silke",
        "last": "Kirschbaum",
        "codes": [
          "SFT",
          "N",
          "O",
          "O",
          "4",
          "O",
          "O",
          "N2",
          "O",
          "IBF",
          "IBF",
          "4",
          "7",
          "O",
          "O",
          "4",
          "4",
          "O",
          "10",
          "O",
          "O",
          "O",
          "4",
          "4",
          "O",
          "O",
          "7",
          "O"
        ]
      },
      {
        "first": "Simone",
        "last": "Kopp",
        "codes": [
          "O",
          "5",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "5",
          "O",
          "N",
          "O",
          "O",
          "7",
          "O",
          "O",
          "O",
          "5",
          "O",
          "O",
          "O",
          "7",
          "O",
          "N",
          "O",
          "O"
        ]
      },
      {
        "first": "Stephanie",
        "last": "Lieblang",
        "codes": [
          "N2",
          "O",
          "4",
          "2",
          "5",
          "7",
          "ST",
          "O",
          "5",
          "5",
          "5",
          "10",
          "4",
          "SF",
          "O",
          "5",
          "N",
          "O",
          "7",
          "2",
          "O",
          "O",
          "N",
          "O",
          "4",
          "10",
          "5",
          "N2"
        ]
      },
      {
        "first": "Astrid",
        "last": "Schneider",
        "codes": [
          "O",
          "2",
          "7",
          "5",
          "5",
          "N",
          "O",
          "O",
          "5",
          "10",
          "O",
          "7",
          "2",
          "O",
          "O",
          "5",
          "10",
          "5",
          "5",
          "O",
          "O",
          "ST",
          "5",
          "N",
          "O",
          "5",
          "5",
          "SF"
        ]
      }
    ]
  },
  {
    "file": "März 2026.csv",
    "start": "01.03.2026",
    "end": "31.03.2026",
    "year": 2026,
    "month": 3,
    "person": {
      "last": "Bitzer",
      "first": "Jan",
      "soll": "171,60",
      "ist": "169,25",
      "urlaub": "33/22"
    },
    "days": [
      {
        "day": 1,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 2,
        "weekday": "MO",
        "code": "U"
      },
      {
        "day": 3,
        "weekday": "DI",
        "code": "U"
      },
      {
        "day": 4,
        "weekday": "MI",
        "code": "U"
      },
      {
        "day": 5,
        "weekday": "DO",
        "code": "U"
      },
      {
        "day": 6,
        "weekday": "FR",
        "code": "U"
      },
      {
        "day": 7,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 8,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 9,
        "weekday": "MO",
        "code": "N"
      },
      {
        "day": 10,
        "weekday": "DI",
        "code": "O"
      },
      {
        "day": 11,
        "weekday": "MI",
        "code": "10"
      },
      {
        "day": 12,
        "weekday": "DO",
        "code": "GSB"
      },
      {
        "day": 13,
        "weekday": "FR",
        "code": "7"
      },
      {
        "day": 14,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 15,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 16,
        "weekday": "MO",
        "code": "N"
      },
      {
        "day": 17,
        "weekday": "DI",
        "code": "O"
      },
      {
        "day": 18,
        "weekday": "MI",
        "code": "10"
      },
      {
        "day": 19,
        "weekday": "DO",
        "code": "GSB"
      },
      {
        "day": 20,
        "weekday": "FR",
        "code": "2"
      },
      {
        "day": 21,
        "weekday": "SA",
        "code": "N2"
      },
      {
        "day": 22,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 23,
        "weekday": "MO",
        "code": "7"
      },
      {
        "day": 24,
        "weekday": "DI",
        "code": "2"
      },
      {
        "day": 25,
        "weekday": "MI",
        "code": "4"
      },
      {
        "day": 26,
        "weekday": "DO",
        "code": "5"
      },
      {
        "day": 27,
        "weekday": "FR",
        "code": "GSB"
      },
      {
        "day": 28,
        "weekday": "SA",
        "code": "SFT"
      },
      {
        "day": 29,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 30,
        "weekday": "MO",
        "code": "7"
      },
      {
        "day": 31,
        "weekday": "DI",
        "code": "10"
      }
    ],
    "team": [
      {
        "first": "Yvonne",
        "last": "Kaiser",
        "codes": [
          "O",
          "4",
          "4",
          "4",
          "4",
          "2",
          "ST",
          "O",
          "7",
          "4",
          "4",
          "4",
          "4",
          "N2",
          "O",
          "4",
          "2",
          "N",
          "O",
          "U",
          "O",
          "O",
          "N",
          "O",
          "4",
          "7",
          "10",
          "O",
          "ST",
          "O",
          "4"
        ]
      },
      {
        "first": "Melanie",
        "last": "Blüm",
        "codes": [
          "O",
          "10",
          "5",
          "2",
          "7",
          "N",
          "O",
          "O",
          "O",
          "7",
          "5",
          "2",
          "10",
          "O",
          "O",
          "5",
          "O",
          "7",
          "5",
          "5",
          "O",
          "N2",
          "O",
          "7",
          "5",
          "5",
          "5",
          "O",
          "SF",
          "N",
          "O"
        ]
      },
      {
        "first": "Silke",
        "last": "Metzger",
        "codes": [
          "O",
          "N",
          "O",
          "10",
          "5",
          "5",
          "N2",
          "O",
          "10",
          "5",
          "7",
          "5",
          "5",
          "SFT",
          "O",
          "4",
          "7",
          "2",
          "N",
          "O",
          "O",
          "O",
          "10",
          "5",
          "5",
          "2",
          "7",
          "O",
          "O",
          "2",
          "5"
        ]
      },
      {
        "first": "Cindy",
        "last": "Braun",
        "codes": [
          "SF",
          "AZV",
          "5",
          "7",
          "2",
          "O",
          "O",
          "N2",
          "O",
          "O",
          "2",
          "10",
          "O",
          "O",
          "O",
          "5",
          "N",
          "O",
          "10",
          "5",
          "O",
          "O",
          "O",
          "O",
          "2",
          "5",
          "N",
          "O",
          "O",
          "O",
          "O"
        ]
      },
      {
        "first": "Monika",
        "last": "Glasser",
        "codes": [
          "O",
          "2",
          "14",
          "14",
          "O",
          "12",
          "O",
          "O",
          "O",
          "14",
          "14",
          "14",
          "14",
          "O",
          "O",
          "12",
          "14",
          "14",
          "O",
          "U",
          "O",
          "O",
          "U",
          "O",
          "12",
          "14",
          "2",
          "O",
          "O",
          "14",
          "14"
        ]
      },
      {
        "first": "Angela",
        "last": "Hassert",
        "codes": [
          "O",
          "7",
          "11",
          "5",
          "N",
          "O",
          "O",
          "O",
          "5",
          "2",
          "N",
          "O",
          "O",
          "O",
          "SF",
          "7",
          "11",
          "O",
          "2",
          "N",
          "O",
          "ST",
          "2",
          "11",
          "7",
          "N",
          "O",
          "O",
          "O",
          "U",
          "U"
        ]
      },
      {
        "first": "Andrea",
        "last": "Kamm",
        "codes": [
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV"
        ]
      },
      {
        "first": "Silke",
        "last": "Kirschbaum",
        "codes": [
          "N2",
          "O",
          "7",
          "4",
          "O",
          "4",
          "O",
          "SFT",
          "O",
          "4",
          "4",
          "N",
          "O",
          "O",
          "O",
          "O",
          "O",
          "4",
          "4",
          "4",
          "O",
          "O",
          "4",
          "4",
          "4",
          "O",
          "O",
          "O",
          "N2",
          "O",
          "7"
        ]
      },
      {
        "first": "Simone",
        "last": "Kopp",
        "codes": [
          "ST",
          "O",
          "5",
          "N",
          "O",
          "5",
          "O",
          "O",
          "O",
          "O",
          "O",
          "5",
          "2",
          "O",
          "N2",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "SF",
          "5",
          "O",
          "5",
          "O",
          "O",
          "O",
          "O",
          "10",
          "N"
        ]
      },
      {
        "first": "Stephanie",
        "last": "Lieblang",
        "codes": [
          "O",
          "5",
          "2",
          "4",
          "5",
          "4",
          "SF",
          "O",
          "4",
          "N",
          "O",
          "7",
          "4",
          "O",
          "ST",
          "2",
          "4",
          "5",
          "7",
          "10",
          "O",
          "O",
          "5",
          "N",
          "O",
          "10",
          "4",
          "N2",
          "O",
          "4",
          "2"
        ]
      },
      {
        "first": "Astrid",
        "last": "Schneider",
        "codes": [
          "O",
          "5",
          "N",
          "O",
          "10",
          "7",
          "O",
          "O",
          "2",
          "10",
          "5",
          "5",
          "N",
          "O",
          "O",
          "5",
          "5",
          "5",
          "5",
          "7",
          "SFT",
          "O",
          "5",
          "5",
          "N",
          "O",
          "5",
          "O",
          "O",
          "U",
          "U"
        ]
      }
    ]
  },
  {
    "file": "April 2026.csv",
    "start": "01.04.2026",
    "end": "30.04.2026",
    "year": 2026,
    "month": 4,
    "person": {
      "last": "Bitzer",
      "first": "Jan",
      "soll": "156,00",
      "ist": "153,75",
      "urlaub": "33/22"
    },
    "days": [
      {
        "day": 1,
        "weekday": "MI",
        "code": "GSB"
      },
      {
        "day": 2,
        "weekday": "DO",
        "code": "4"
      },
      {
        "day": 3,
        "weekday": "FR",
        "code": "O"
      },
      {
        "day": 4,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 5,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 6,
        "weekday": "MO",
        "code": "N2"
      },
      {
        "day": 7,
        "weekday": "DI",
        "code": "N"
      },
      {
        "day": 8,
        "weekday": "MI",
        "code": "O"
      },
      {
        "day": 9,
        "weekday": "DO",
        "code": "5"
      },
      {
        "day": 10,
        "weekday": "FR",
        "code": "7"
      },
      {
        "day": 11,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 12,
        "weekday": "SO",
        "code": "SFT"
      },
      {
        "day": 13,
        "weekday": "MO",
        "code": "7"
      },
      {
        "day": 14,
        "weekday": "DI",
        "code": "2"
      },
      {
        "day": 15,
        "weekday": "MI",
        "code": "5"
      },
      {
        "day": 16,
        "weekday": "DO",
        "code": "10"
      },
      {
        "day": 17,
        "weekday": "FR",
        "code": "GSB"
      },
      {
        "day": 18,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 19,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 20,
        "weekday": "MO",
        "code": "U"
      },
      {
        "day": 21,
        "weekday": "DI",
        "code": "U"
      },
      {
        "day": 22,
        "weekday": "MI",
        "code": "U"
      },
      {
        "day": 23,
        "weekday": "DO",
        "code": "U"
      },
      {
        "day": 24,
        "weekday": "FR",
        "code": "U"
      },
      {
        "day": 25,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 26,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 27,
        "weekday": "MO",
        "code": "N"
      },
      {
        "day": 28,
        "weekday": "DI",
        "code": "O"
      },
      {
        "day": 29,
        "weekday": "MI",
        "code": "10"
      },
      {
        "day": 30,
        "weekday": "DO",
        "code": "7"
      }
    ],
    "team": [
      {
        "first": "Yvonne",
        "last": "Kaiser",
        "codes": [
          "2",
          "4",
          "N2",
          "O",
          "O",
          "O",
          "4",
          "O",
          "4",
          "10",
          "N2",
          "O",
          "4",
          "4",
          "7",
          "4",
          "2",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "4",
          "4",
          "O",
          "2"
        ]
      },
      {
        "first": "Melanie",
        "last": "Blüm",
        "codes": [
          "5",
          "U",
          "O",
          "O",
          "SFT",
          "O",
          "7",
          "5",
          "O",
          "O",
          "O",
          "O",
          "2",
          "5",
          "10",
          "5",
          "N",
          "O",
          "O",
          "2",
          "7",
          "10",
          "5",
          "5",
          "N2",
          "O",
          "O",
          "2",
          "O",
          "O"
        ]
      },
      {
        "first": "Silke",
        "last": "Metzger",
        "codes": [
          "7",
          "5",
          "O",
          "SFT",
          "O",
          "O",
          "2",
          "7",
          "10",
          "5",
          "O",
          "O",
          "4",
          "10",
          "5",
          "N",
          "O",
          "O",
          "SFT",
          "N",
          "O",
          "5",
          "7",
          "2",
          "SF",
          "O",
          "2",
          "N",
          "O",
          "10"
        ]
      },
      {
        "first": "Cindy",
        "last": "Braun",
        "codes": [
          "U",
          "N",
          "O",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "O",
          "N",
          "O",
          "O",
          "5",
          "SF",
          "O",
          "7",
          "O",
          "O",
          "10",
          "N",
          "O",
          "O",
          "O",
          "7",
          "2",
          "U"
        ]
      },
      {
        "first": "Monika",
        "last": "Glasser",
        "codes": [
          "O",
          "12",
          "O",
          "O",
          "O",
          "O",
          "14",
          "O",
          "2",
          "14",
          "O",
          "O",
          "12",
          "14",
          "2",
          "14",
          "O",
          "O",
          "O",
          "14",
          "14",
          "14",
          "2",
          "O",
          "O",
          "O",
          "14",
          "12",
          "O",
          "14"
        ]
      },
      {
        "first": "Angela",
        "last": "Hassert",
        "codes": [
          "11",
          "7",
          "O",
          "N2",
          "O",
          "O",
          "5",
          "2",
          "5",
          "N",
          "O",
          "O",
          "5",
          "7",
          "N",
          "O",
          "11",
          "ST",
          "O",
          "5",
          "2",
          "N",
          "O",
          "5",
          "O",
          "O",
          "5",
          "5",
          "N",
          "O"
        ]
      },
      {
        "first": "Andrea",
        "last": "Kamm",
        "codes": [
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV"
        ]
      },
      {
        "first": "Silke",
        "last": "Kirschbaum",
        "codes": [
          "4",
          "O",
          "O",
          "O",
          "O",
          "SFT",
          "O",
          "N",
          "O",
          "O",
          "O",
          "N2",
          "O",
          "4",
          "O",
          "7",
          "O",
          "O",
          "O",
          "4",
          "N",
          "O",
          "4",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U"
        ]
      },
      {
        "first": "Simone",
        "last": "Kopp",
        "codes": [
          "O",
          "2",
          "SFT",
          "O",
          "O",
          "O",
          "O",
          "10",
          "N",
          "O",
          "SF",
          "O",
          "O",
          "O",
          "O",
          "2",
          "5",
          "O",
          "N2",
          "O",
          "5",
          "O",
          "O",
          "10",
          "O",
          "O",
          "7",
          "O",
          "N",
          "O"
        ]
      },
      {
        "first": "Stephanie",
        "last": "Lieblang",
        "codes": [
          "N",
          "O",
          "O",
          "O",
          "N2",
          "O",
          "10",
          "5",
          "7",
          "2",
          "ST",
          "O",
          "N",
          "O",
          "U",
          "U",
          "U",
          "O",
          "O",
          "10",
          "4",
          "2",
          "4",
          "7",
          "ST",
          "N2",
          "O",
          "4",
          "5",
          "5"
        ]
      },
      {
        "first": "Astrid",
        "last": "Schneider",
        "codes": [
          "U",
          "U",
          "O",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "AZV",
          "7",
          "N2",
          "O",
          "O",
          "10",
          "7",
          "N",
          "O",
          "O",
          "SFT",
          "10",
          "O",
          "7",
          "N"
        ]
      }
    ]
  },
  {
    "file": "Mai 2026.csv",
    "start": "01.05.2026",
    "end": "31.05.2026",
    "year": 2026,
    "month": 5,
    "person": {
      "last": "Bitzer",
      "first": "Jan",
      "soll": "140,40",
      "ist": "146,30",
      "urlaub": "33/21"
    },
    "days": [
      {
        "day": 1,
        "weekday": "FR",
        "code": "O"
      },
      {
        "day": 2,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 3,
        "weekday": "SO",
        "code": "SFT"
      },
      {
        "day": 4,
        "weekday": "MO",
        "code": "N"
      },
      {
        "day": 5,
        "weekday": "DI",
        "code": "O"
      },
      {
        "day": 6,
        "weekday": "MI",
        "code": "10"
      },
      {
        "day": 7,
        "weekday": "DO",
        "code": "7"
      },
      {
        "day": 8,
        "weekday": "FR",
        "code": "4"
      },
      {
        "day": 9,
        "weekday": "SA",
        "code": "ST"
      },
      {
        "day": 10,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 11,
        "weekday": "MO",
        "code": "N"
      },
      {
        "day": 12,
        "weekday": "DI",
        "code": "O"
      },
      {
        "day": 13,
        "weekday": "MI",
        "code": "7"
      },
      {
        "day": 14,
        "weekday": "DO",
        "code": "ST"
      },
      {
        "day": 15,
        "weekday": "FR",
        "code": "AZV"
      },
      {
        "day": 16,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 17,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 18,
        "weekday": "MO",
        "code": "2"
      },
      {
        "day": 19,
        "weekday": "DI",
        "code": "5"
      },
      {
        "day": 20,
        "weekday": "MI",
        "code": "GSB"
      },
      {
        "day": 21,
        "weekday": "DO",
        "code": "5"
      },
      {
        "day": 22,
        "weekday": "FR",
        "code": "10"
      },
      {
        "day": 23,
        "weekday": "SA",
        "code": "N2"
      },
      {
        "day": 24,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 25,
        "weekday": "MO",
        "code": "O"
      },
      {
        "day": 26,
        "weekday": "DI",
        "code": "2"
      },
      {
        "day": 27,
        "weekday": "MI",
        "code": "4"
      },
      {
        "day": 28,
        "weekday": "DO",
        "code": "N"
      },
      {
        "day": 29,
        "weekday": "FR",
        "code": "O"
      },
      {
        "day": 30,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 31,
        "weekday": "SO",
        "code": "O"
      }
    ],
    "team": [
      {
        "first": "Yvonne",
        "last": "Kaiser",
        "codes": [
          "N2",
          "O",
          "O",
          "7",
          "2",
          "N",
          "O",
          "4",
          "O",
          "N2",
          "O",
          "4",
          "4",
          "O",
          "O",
          "O",
          "ST",
          "N",
          "O",
          "5",
          "4",
          "2",
          "O",
          "O",
          "ST",
          "4",
          "4",
          "O",
          "4",
          "N2",
          "O"
        ]
      },
      {
        "first": "Melanie",
        "last": "Blüm",
        "codes": [
          "SF",
          "O",
          "N2",
          "O",
          "O",
          "2",
          "10",
          "7",
          "O",
          "O",
          "U",
          "U",
          "U",
          "O",
          "AZV",
          "O",
          "O",
          "O",
          "O",
          "7",
          "10",
          "O",
          "ST",
          "O",
          "O",
          "5",
          "2",
          "7",
          "5",
          "O",
          "N2"
        ]
      },
      {
        "first": "Silke",
        "last": "Metzger",
        "codes": [
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "7",
          "N",
          "O",
          "O",
          "2",
          "N2",
          "O",
          "10",
          "7",
          "O",
          "2",
          "5",
          "O",
          "SFT",
          "O",
          "N",
          "O",
          "5",
          "5",
          "SFT",
          "O"
        ]
      },
      {
        "first": "Cindy",
        "last": "Braun",
        "codes": [
          "O",
          "O",
          "O",
          "DB",
          "7",
          "O",
          "2",
          "N",
          "O",
          "ST",
          "10",
          "O",
          "2",
          "O",
          "5",
          "O",
          "N2",
          "O",
          "O",
          "10",
          "O",
          "O",
          "SF",
          "O",
          "O",
          "10",
          "O",
          "O",
          "7",
          "O",
          "O"
        ]
      },
      {
        "first": "Monika",
        "last": "Glasser",
        "codes": [
          "O",
          "O",
          "O",
          "2",
          "14",
          "14",
          "O",
          "12",
          "O",
          "O",
          "14",
          "14",
          "U",
          "O",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "O",
          "O",
          "12",
          "14",
          "2",
          "O",
          "O"
        ]
      },
      {
        "first": "Angela",
        "last": "Hassert",
        "codes": [
          "ST",
          "O",
          "O",
          "O",
          "N",
          "O",
          "5",
          "2",
          "SF",
          "O",
          "O",
          "5",
          "N",
          "O",
          "7",
          "O",
          "SF",
          "5",
          "N",
          "O",
          "U",
          "U",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O"
        ]
      },
      {
        "first": "Andrea",
        "last": "Kamm",
        "codes": [
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "BV",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS"
        ]
      },
      {
        "first": "Silke",
        "last": "Kirschbaum",
        "codes": [
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "4",
          "4",
          "4",
          "O",
          "10",
          "O",
          "O",
          "O",
          "O",
          "N",
          "O",
          "7",
          "O",
          "O",
          "N2",
          "O",
          "7",
          "10",
          "O",
          "O",
          "SFT"
        ]
      },
      {
        "first": "Simone",
        "last": "Kopp",
        "codes": [
          "O",
          "SF",
          "O",
          "5",
          "O",
          "7",
          "O",
          "O",
          "N2",
          "O",
          "O",
          "2",
          "O",
          "SF",
          "N",
          "O",
          "O",
          "O",
          "10",
          "O",
          "N",
          "O",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O"
        ]
      },
      {
        "first": "Stephanie",
        "last": "Lieblang",
        "codes": [
          "O",
          "N2",
          "O",
          "10",
          "5",
          "5",
          "5",
          "5",
          "O",
          "SF",
          "5",
          "10",
          "5",
          "N2",
          "O",
          "O",
          "O",
          "7",
          "5",
          "2",
          "5",
          "5",
          "O",
          "N2",
          "O",
          "7",
          "5",
          "2",
          "N",
          "O",
          "O"
        ]
      },
      {
        "first": "Astrid",
        "last": "Schneider",
        "codes": [
          "O",
          "ST",
          "O",
          "5",
          "10",
          "O",
          "N",
          "O",
          "O",
          "O",
          "2",
          "7",
          "10",
          "O",
          "5",
          "SFT",
          "O",
          "5",
          "2",
          "O",
          "7",
          "N",
          "O",
          "O",
          "SF",
          "5",
          "N",
          "O",
          "10",
          "O",
          "O"
        ]
      }
    ]
  },
  {
    "file": "Juli 2026.csv",
    "start": "01.07.2026",
    "end": "31.07.2026",
    "year": 2026,
    "month": 7,
    "person": {
      "last": "Bitzer",
      "first": "Jan",
      "soll": "179,40",
      "ist": "179,50",
      "urlaub": "33/21"
    },
    "days": [
      {
        "day": 1,
        "weekday": "MI",
        "code": "4"
      },
      {
        "day": 2,
        "weekday": "DO",
        "code": "10"
      },
      {
        "day": 3,
        "weekday": "FR",
        "code": "GSB"
      },
      {
        "day": 4,
        "weekday": "SA",
        "code": "N2"
      },
      {
        "day": 5,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 6,
        "weekday": "MO",
        "code": "10"
      },
      {
        "day": 7,
        "weekday": "DI",
        "code": "5"
      },
      {
        "day": 8,
        "weekday": "MI",
        "code": "5"
      },
      {
        "day": 9,
        "weekday": "DO",
        "code": "N"
      },
      {
        "day": 10,
        "weekday": "FR",
        "code": "O"
      },
      {
        "day": 11,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 12,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 13,
        "weekday": "MO",
        "code": "U"
      },
      {
        "day": 14,
        "weekday": "DI",
        "code": "U"
      },
      {
        "day": 15,
        "weekday": "MI",
        "code": "U"
      },
      {
        "day": 16,
        "weekday": "DO",
        "code": "U"
      },
      {
        "day": 17,
        "weekday": "FR",
        "code": "U"
      },
      {
        "day": 18,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 19,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 20,
        "weekday": "MO",
        "code": "U"
      },
      {
        "day": 21,
        "weekday": "DI",
        "code": "U"
      },
      {
        "day": 22,
        "weekday": "MI",
        "code": "U"
      },
      {
        "day": 23,
        "weekday": "DO",
        "code": "U"
      },
      {
        "day": 24,
        "weekday": "FR",
        "code": "U"
      },
      {
        "day": 25,
        "weekday": "SA",
        "code": "O"
      },
      {
        "day": 26,
        "weekday": "SO",
        "code": "O"
      },
      {
        "day": 27,
        "weekday": "MO",
        "code": "7"
      },
      {
        "day": 28,
        "weekday": "DI",
        "code": "5"
      },
      {
        "day": 29,
        "weekday": "MI",
        "code": "2"
      },
      {
        "day": 30,
        "weekday": "DO",
        "code": "5"
      },
      {
        "day": 31,
        "weekday": "FR",
        "code": "5"
      }
    ],
    "team": [
      {
        "first": "Yvonne",
        "last": "Kaiser",
        "codes": [
          "U",
          "N",
          "O",
          "O",
          "ST",
          "4",
          "7",
          "2",
          "4",
          "4",
          "N2",
          "O",
          "2",
          "4",
          "N",
          "O",
          "AZV",
          "O",
          "O",
          "O",
          "N",
          "O",
          "4",
          "10",
          "O",
          "O",
          "4",
          "2",
          "N",
          "O",
          "7"
        ]
      },
      {
        "first": "Melanie",
        "last": "Blüm",
        "codes": [
          "N",
          "O",
          "5",
          "SFT",
          "O",
          "2",
          "10",
          "7",
          "O",
          "O",
          "O",
          "SF",
          "10",
          "O",
          "O",
          "2",
          "7",
          "O",
          "N2",
          "O",
          "7",
          "10",
          "5",
          "2",
          "O",
          "O",
          "N",
          "O",
          "7",
          "O",
          "5"
        ]
      },
      {
        "first": "Silke",
        "last": "Metzger",
        "codes": [
          "2",
          "7",
          "5",
          "O",
          "O",
          "7",
          "2",
          "10",
          "5",
          "N",
          "O",
          "O",
          "5",
          "7",
          "10",
          "5",
          "2",
          "SFT",
          "O",
          "10",
          "4",
          "5",
          "7",
          "5",
          "N2",
          "O",
          "10",
          "N",
          "O",
          "5",
          "2"
        ]
      },
      {
        "first": "Cindy",
        "last": "Braun",
        "codes": [
          "7",
          "2",
          "N",
          "O",
          "SF",
          "5",
          "O",
          "N",
          "O",
          "O",
          "O",
          "ST",
          "O",
          "N",
          "O",
          "10",
          "O",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U"
        ]
      },
      {
        "first": "Monika",
        "last": "Glasser",
        "codes": [
          "12",
          "O",
          "2",
          "O",
          "O",
          "14",
          "14",
          "O",
          "2",
          "12",
          "O",
          "O",
          "14",
          "14",
          "2",
          "O",
          "14",
          "O",
          "O",
          "14",
          "12",
          "O",
          "14",
          "14",
          "O",
          "O",
          "14",
          "O",
          "U",
          "U",
          "U"
        ]
      },
      {
        "first": "Angela",
        "last": "Hassert",
        "codes": [
          "5",
          "5",
          "11",
          "O",
          "O",
          "N",
          "O",
          "5",
          "7",
          "2",
          "SF",
          "N2",
          "O",
          "11",
          "5",
          "N",
          "O",
          "O",
          "O",
          "O",
          "O",
          "7",
          "2",
          "N",
          "O",
          "O",
          "2",
          "7",
          "11",
          "N",
          "O"
        ]
      },
      {
        "first": "Andrea",
        "last": "Kamm",
        "codes": [
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS",
          "MS"
        ]
      },
      {
        "first": "Silke",
        "last": "Kirschbaum",
        "codes": [
          "O",
          "4",
          "7",
          "O",
          "N2",
          "O",
          "O",
          "O",
          "10",
          "7",
          "O",
          "O",
          "7",
          "4",
          "4",
          "O",
          "4",
          "O",
          "O",
          "4",
          "4",
          "N",
          "O",
          "O",
          "O",
          "SFT",
          "O",
          "O",
          "4",
          "10",
          "O"
        ]
      },
      {
        "first": "Simone",
        "last": "Kopp",
        "codes": [
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "N",
          "O",
          "O",
          "5",
          "ST",
          "O",
          "N",
          "O",
          "7",
          "5",
          "N",
          "O",
          "ST",
          "2",
          "O",
          "5",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O",
          "O"
        ]
      },
      {
        "first": "Stephanie",
        "last": "Lieblang",
        "codes": [
          "AZV",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "SF",
          "N",
          "O",
          "2",
          "10",
          "7",
          "O",
          "N2",
          "O",
          "5",
          "5",
          "2",
          "10"
        ]
      },
      {
        "first": "Astrid",
        "last": "Schneider",
        "codes": [
          "U",
          "U",
          "U",
          "O",
          "O",
          "U",
          "U",
          "U",
          "U",
          "U",
          "O",
          "O",
          "O",
          "1",
          "O",
          "7",
          "10",
          "N2",
          "O",
          "7",
          "2",
          "O",
          "N",
          "O",
          "SFT",
          "O",
          "5",
          "10",
          "O",
          "7",
          "N"
        ]
      }
    ]
  }
];
